### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by huAlahdal** [nalaso/windai#3]
i added the database but i don't understand what you mean by Authentication. are Database and Authentication need to be in .env or is there other things need to be in?

# Database
DATABASE_URL="mongodb+srv://<user>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority"

# Authentication
AUTH_SECRET=your_auth_secret
AUTH_GITHUB_ID=your_auth_github_id
AUTH_GITHUB_SECRET=your_auth_github_secret

**Comment by nalaso** [comment]
Wow that’s the first issue

Those are the configurations for nextatuh.

You can get AUTH_GITHUB_ID and AUTH_GITHUB_SECRET from https://github.com/settings/developers

For AUTH_SECRET, see  https://authjs.dev/getting-started/deployment#auth_secret.
